[device]
name = UV camera
label = PIProEM512Excelon
path = camera_test/PIProEM512Excelon
driver = PIProEM512Excelon
constr_params = demo
correct_response = not implemented
slow_data = False
row = 0
column = 0
plots_queue_maxlen = 1000
max_NaN_count = 0
meta_device = False
plots_fn = y * self.dset_attrs[-1][self.config["y"].strip()+" : gain"] + self.dset_attrs[-1][self.config["y"].strip()+" : offset"]

[attributes]
column_names = 
units = 

[enabled]
label = Device enabled
type = QCheckBox
tristate = True
row = 1
col = 0
tooltip = Whether or not device is enabled
rowspan = None
colspan = None
value = 1

[HDF_enabled]
label = HDF enabled
type = QCheckBox
row = 1
col = 1
tooltip = Whether or not writing to HDF file
rowspan = None
colspan = None
value = True

[demo]
label = Demo camera
type = QCheckBox
row = 1
col = 2
tooltip = Can use virtual camera for testing
rowspan = None
colspan = None
value = True

[dt]
label = Loop delay [s]
type = QLineEdit
row = 2
col = 1
tooltip = None
rowspan = None
colspan = None
value = 0.01
enter_cmd = None

[EM_gain]
label = EM Gain
type = QLineEdit
row = 3
col = 1
tooltip = EM gain
rowspan = None
colspan = None
value = 1
enter_cmd = None

[CCD_temp]
label = CCD Temp set point
type = QLineEdit
row = 4
col = 1
tooltip = Temperature of camera CCD
rowspan = None
colspan = None
value = -70
enter_cmd = None